### ISSUE TITLE
NativeInner - Product details - Add to cart

### ISSUE THREAD

**Issue by Quynhnn19409** [Simicart/siminia-public#224]
# 🐞 Add to cart với qty lớn hơn stock, vẫn báo thành công

 
1. Step: Mở detail sản phẩm > Nhấn Add to cart > Nhập Qty lớn hơn Stock (ví dụ 100000) > Nhấn Add to cart 
2. Actual: hiện thông báo thành công, cart không update qty
3. Evidence: https://slack-files.com/T1H1CATTM-F039DV6ABNZ-3cc489019c 
4. Expect: Hiện thông báo lỗi, ví dụ: "The requested qty is not available"...

**Comment by duynguyen0702** [comment]
Đã fix xong bug Add to cart với qty lớn hơn stock

**Comment by codynguyen1** [comment]
Resolved
