### ISSUE TITLE
Related products is broken at the first time.

### ISSUE THREAD

**Issue by MaxTa91** [Simicart/siminia-public#23]
# 🐞 Report

### Description

 When customer open a product detail page which has the related product. This section products is broken at the first time. 

### Exception/Error message

<pre><code>

![Screen Shot 2022-01-11 at 13 49 10](https://user-images.githubusercontent.com/11706605/148894738-7dab7406-62d1-4316-8c41-b680af356ea5.png)

https://magento.pwa-commerce.com/ryker-lumatech-trade-tee-v-neck.html 

</code></pre>

### Your environment

https://magento.pwa-commerce.com/ryker-lumatech-trade-tee-v-neck.html
Mac OS
### Expected behaviour

Make them clear as we reload this page.

**Comment by codynguyen1** [comment]
Fixed with commit
https://github.com/Simicart/siminia-public/commit/00bf184db5d74db441a539a7ba47e7f22c4834f5
