### ISSUE TITLE
NativeInner - Add new address 

### ISSUE THREAD

**Issue by Quynhnn19409** [Simicart/siminia-public#230]
# 🚀 Hiển thị keyboard số

### Với các field chỉ cho phép nhập số, ví dụ Phone, VAT thì chỉ cần hiển thị keyboard số, hiện tại đang hiện keyboard gồm cả chữ cái: https://prnt.sc/97awyQg-7PLt

**Comment by duynguyen0702** [comment]
Đã fix bug keyboard
