### ISSUE TITLE
NativeInner - Wishlist - Không nhấn icon share được

### ISSUE THREAD

**Issue by Quynhnn19409** [Simicart/siminia-public#234]
### Actual: Nhấn icon Share ở wishlist > không có action gì
Expect: Nhấn icon Share > có thể share link sp qua các nền tảng khác

**Comment by Quynhnn19409** [comment]
6/4: Nhấn icon Share đã có action, nhưng:
1. Pinterest: nhấn vào không redirect sang trang tương ứng để share wishlist
2. Mail: Nhấn vào báo lỗi: https://prnt.sc/GGbr03uIjRSH 
3. Facebook và Twitter: bị lỗi header và không đóng đc sau khi share: https://prnt.sc/topv9BHqfa0R ; https://prnt.sc/aHkrvYJ7AVDX 
4. Share thành công, nhấn vào link share > hiện wishlist empty: https://prnt.sc/YRJ6g75jok2A

**Comment by Quynhnn19409** [comment]
12/4: Còn bug Share thành công, nhấn vào link share > hiện wishlist empty: https://slack-files.com/T1H1CATTM-F03B3GW5M42-c21f976e46

**Comment by Quynhnn19409** [comment]
15/4: Đã hiện wishlist, nhưng cần chỉnh giao diện: https://prnt.sc/uYvvbG6g4iOj

**Comment by duynguyen0702** [comment]
Đã update theo theme mới
