### ISSUE TITLE
NativeInner - Social login không thành công

### ISSUE THREAD

**Issue by Quynhnn19409** [Simicart/siminia-public#250]
### Social login báo lỗi
Actual:
1. Google: https://prnt.sc/CearVSIAwPKe
2. Facebook: https://prnt.sc/_ddNI-gfPQOg 
3. LinkedIn: https://prnt.sc/P_yVLqolmnDc 
Expect: Login thành công

**Comment by duynguyen0702** [comment]
Đã fix xong bug Social
