### ISSUE TITLE
Product listing page - Missing show in&ex Tax

### ISSUE THREAD

**Issue by MaxTa91** [Simicart/siminia-public#26]
# 🐞 Report

### Description

Not showing price Included and excluded Tax.
### Exception/Error message
Go to admin -- Configured show products included, excluded Tax.
On FE ---> It just show the price (exTax)
### Your environment

https://magento.pwa-commerce.com/men/tops-men/jackets-men.html

### Expected behaviour
Need to follow Magento configuration.

**Comment by codynguyen1** [comment]
Fixed along with issue No.36
