### ISSUE TITLE
Total cart page - Missing show in&ex Tax

### ISSUE THREAD

**Issue by MaxTa91** [Simicart/siminia-public#27]
# 🐞 Report

### Description

Not showing price Included and excluded Tax.
### Exception/Error message
Go to admin -- Configured show total included, excluded Tax.
On FE ---> It just show the price (exTax)

### Your environment
https://magento.pwa-commerce.com/

### Expected behaviour

Need to follow Magento configuration.

**Comment by codynguyen1** [comment]
Same issue with this
https://github.com/Simicart/siminia-public/issues/99
Solved with this PR:
https://github.com/Simicart/siminia-public/pull/237
