### ISSUE TITLE
Total order history -  Missing show in&ex Tax

### ISSUE THREAD

**Issue by MaxTa91** [Simicart/siminia-public#28]
# 🐞 Report

### Description

Not showing price Included and excluded Tax.

### Exception/Error message

Go to admin -- Configured show total included, excluded Tax.

### Your environment

https://magento.pwa-commerce.com/

### Expected behaviour

Need to follow Magento configuration.

**Comment by Watch3ruk** [comment]
it actually shows both - even if store config is set to no : 
![Garden Haven - Google Chrome 12_01_2022 14_38_19](https://user-images.githubusercontent.com/48841019/149161016-b58ce0b1-c2ce-42d4-a379-77b8efb3d269.png)
![Garden Haven - Google Chrome 12_01_2022 14_38_09](https://user-images.githubusercontent.com/48841019/149161023-a67890d3-6809-473b-8ef6-c98434dab0ea.png)

**Comment by codynguyen1** [comment]
Resolved (showing excl. incld. price following backend configuration)
