### ISSUE TITLE
Gift card - bugs

### ISSUE THREAD

**Issue by Quynhnn19409** [Simicart/siminia-public#316]
# 🐞 Một số issue
1. Không đóng được pop-up review: https://screenrec.com/share/TfzOxhP0qB > expect: đóng được pop-up
2. Không upload được image: https://screenrec.com/share/G5YufCSF42 > expect: upload ảnh thành công
3. Giao diện: Image không sát lề trái: https://prnt.sc/BOgpkEON9AjO 
4. Không hiện giá sp: https://prnt.sc/Nh5nXntaV8K6 , giá hiện ở cart như này: https://prnt.sc/NxNSgtDHmiQN > expect hiển thị giá gift card.
5. Add to wishlist thành công, icon wish list đổi màu, nhưng mở Wishlist ra thì không có sản phẩm gift card: https://screenrec.com/share/rJKWRfUnX3 > expect: hiển thị gift card trong wishlist
6. Order detail không hiển thị thông tin có sử dụng gift card: https://prnt.sc/7L_5VyyXiFy2 > expect: hiển thị thông tin gift card đã sử dụng.
7. Gift card gửi về email người nhận, font chữ màu trắng nên trùng với background: https://prnt.sc/IGJui_XRHr3F > expect: chỉnh ảnh backgroud cho rộng full màn hoặc đổi màu font chữ.
8. Không place order được: https://screenrec.com/share/Nc9Jl2Cvkh 
chọn sp https://nam.pwa-commerce.com/test-gift-card-email.html là sp có Delivery: Print at home > check out > nhập address > không save được để check out.

**Comment by quochung26** [comment]
Đã fix bug 1,2,5,8
Bug 3 thấy site thường đang như vậy https://prnt.sc/s3pPqCxfCYwT
Bug 4 Lỗi do extension call for price cần review lại
Bug 6 Thiếu api order detail chờ bên mageplaza thêm

**Comment by Quynhnn19409** [comment]
16/05: Số 1,2,5,8 đã test xong > Ok

**Comment by duynguyen0702** [comment]
Đã fix bug 3,4,6
