### ISSUE TITLE
Can we make it compatible with PWA studio 12.4

### ISSUE THREAD

**Issue by SyedWaqasNabi** [Simicart/siminia-public#328]
We are facing problem using PWA studio 12.4 and have some components that works on 12.4 but it is not working with 12.0. The issue is venia ui 9.4 and peregrine 12.4.0. We are getting errors and some css problem. Can you guys make it compatible with 12.4 version of PWA studio.

**Comment by codynguyen1** [comment]
Yes @SyedWaqasNabi  we have plan to update this project to work with pwa-studio version 12.4, thank you for your feedback!

**Comment by SyedWaqasNabi** [comment]
Thanks for the reply @codynguyen1 when it can be release. We have some customer that want to use it and we want to know when it become compatible.

**Comment by codynguyen1** [comment]
Hi @SyedWaqasNabi, the latest version supports pwa-studio 12.6 has just got released
