### ISSUE TITLE
Problem with deploy to Magento Cloud

### ISSUE THREAD

**Issue by kevincarcache-omni** [Simicart/siminia-public#332]
# 🐞 Report

### Description

When we deploy siminia to Magento Cloud, some of the static files give us a 404 status, like core-theme-style.css and some png files

### 🔬 Minimal Reproduction

- deploy the magento cloud environment
- in the magento cloud build hook there is a script that excecute yarn install and yarn build
- CONFIG__DEFAULT__WEB__UPWARD__PATH=/app/<proyect_id>/pwa/upward.yml
- We go to the deployed website

### Exception/Error message

We got errors trying to download the css and pngs files
<pre><code>
Refused to apply style from 'https://&lt;magentosite&gt;/static/core-theme-style.css?v=12.0.0' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

Failed to load resource: the server responded with a status of 404 (Not Found) [loading_ic.svg:1]
Failed to load resource: the server responded with a status of 404 (Not Found) [/static/icons/siminia_circle_512.png:1]

Error while trying to use the following icon from the Manifest: https://&lt;magentosite&gt;/static/icons/siminia_circle_512.png (Download error or resource isn't a valid image)

Refused to apply style from 'https://&lt;magentosite&gt;/static/core-theme-style.css?v=12.0.0' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
</code></pre>

### Your environment

Magento Cloud (Linux)

### Expected behaviour

The website shows the same styles like the demo page https://magento.pwa-commerce.com/

### Possible solution

We thing that it has something to do with the upward.yml configuration

**Comment by codynguyen1** [comment]
Hi @kevincarcache-omni , the content from static folder of pwa-studio dist directory has to be synchronized with static folder of magento directory, please make sure the files at the path mentioned above exist.
