### ISSUE TITLE
Excl. Tax  Incl. Tax on is shown on all Products 

### ISSUE THREAD

**Issue by Watch3ruk** [Simicart/siminia-public#36]
🐞 Report

Excl. Tax  Incl. Tax on is shown on all Products , apart from US ( that i know of VAT is always added to main price ) could be a good feature for B2B. 

### Expected behaviour
Only price including Tax is shown . 

### Possible solution
![Garden Haven - Google Chrome 12_01_2022 14_38_09](https://user-images.githubusercontent.com/48841019/149162818-7e5b9e1b-fefd-44f4-acf6-b6a3c83d953c.png)

**Comment by codynguyen1** [comment]
@Watch3ruk  on listing product, we can always change the tax display using the file below:
https://github.com/Simicart/siminia-public/blob/master/src/simi/Helper/Pricing.js
I changed it to included (2)

**Comment by Watch3ruk** [comment]
thanks .
