### ISSUE TITLE
Menus do not deactivate properly

### ISSUE THREAD

**Issue by fvlasie** [Simicart/siminia-public#363]
# 🐞 Report

### Description

Menus do not deactivate properly.

### 🔬 Minimal Reproduction

See this screen recording:

https://user-images.githubusercontent.com/33334298/203674770-37bc26fc-6c54-4245-81b6-993da7705080.mov

### Your environment

Safari 16.1 on MacOS Monterey (Intel)

Problem does not show in Blisk (same platform)

**Comment by Long090501** [comment]
Bug has been fixed on latest mega menu version (on branch 13.0/develop)

**Comment by Long090501** [comment]
Bug has been fixed on latest mega menu version (on branch 13.0/develop)
