### ISSUE TITLE
Mobile Navigation Missing on Product View

### ISSUE THREAD

**Issue by fvlasie** [Simicart/siminia-public#364]
# 🐞 Report

### Description

When viewing a product at phone screen size the navigation bar does not show. This makes it hard for the user to go back home or exit the product detail view.

### 🔬 Minimal Reproduction

Please see screen recording:

https://user-images.githubusercontent.com/33334298/203675753-d64dc20a-f563-4569-a274-d85c8e88ea7d.mov

### Your environment

Any environmet.

### Expected behaviour

Nav bar should show on all pages at mobile screen sizes.

**Comment by Long090501** [comment]
This issue has already been fixed
