### ISSUE TITLE
Mobile Page view - UI adjustment . 

### ISSUE THREAD

**Issue by Watch3ruk** [Simicart/siminia-public#39]
🚀 feature request

When browsing categories items don't align when there's a review or Title extends to 2 lines and has "As low as" 
* like icon is outside of the container for product 
![s1](https://user-images.githubusercontent.com/48841019/149177041-ce90c969-bff0-4309-8300-6b161555dd3a.png)

that could use some improvement : 
_i would suggest having an option for : **As low as** it could be replaced by "from :"_ 
![s2](https://user-images.githubusercontent.com/48841019/149177048-41566d0a-d63d-44f3-b731-c1c83f8626e7.png)

### Describe the solution you'd like

ideas : 
✍️ - greyed out starts for no reviews items 
✍️ - no idea how to get the title :/ set to take 2 lines ?

**Comment by codynguyen1** [comment]
Solved with PR #42
