### ISSUE TITLE
Additional Attributes 

### ISSUE THREAD

**Issue by Watch3ruk** [Simicart/siminia-public#43]
🐞 Report
Adding Custom Attributes to Vania in 12.0 requires changes in : 
`/@magento/packages/peregrine/lib/talons/RootComponents/Product/productDetailFragment.gql.js`
 
i presume that to do this same in Simi we need to change : 

`/../siminia/src/simi/talons/TapitaPageBuilder/useProducts.js  ? `

are you planning on adding the additional attributes that will be released in 12.2 ?

**Comment by codynguyen1** [comment]
@Watch3ruk  yes we will bring the attribute feature from new version of pwa-studio to this package when it's fully reviewed and tested.

**Comment by codynguyen1** [comment]
@Watch3ruk  the custom attribute feature got released on 12.2 version of pwa-studio, but it's not working with default magento 2.4.3, so to keep this package running on magento 2.4.3, we will submit it on new branch (12.2/develop) for newer version of magento in the future.

**Comment by codynguyen1** [comment]
@Watch3ruk  As the meta packages is not included to magento by default, the pwa-studio from 12.2 version will need to run on magento sites that got meta package installed:
https://github.com/magento/magento2-pwa
I added a flag to template.phtml so it's disabled by default, but when you turn it on, the custom attributes would be added to query content (SM_ENABLE_META_PACKAGES)

**Comment by codynguyen1** [comment]
Related commit: 
https://github.com/Simicart/siminia-public/commit/83e128b15b89e94d89ea521260abde87f1172b07
