### ISSUE TITLE
Product Label Feature

### ISSUE THREAD

**Issue by codynguyen1** [Simicart/siminia-public#5]
Product Label Feature following:
https://github.com/Simicart/productlabel-module-pwa-studio

**Comment by MaxTa91** [comment]
@hieubachvan 
1. Showing the incorrect position https://domaio.pwa-commerce.com/men/tops-men/jackets-men.html ---> Please check my configuration. 
2. I think it is not working with some settings as color, label, css. Please check with Cody. 
3. https://domaio.pwa-commerce.com/gear/fitness-equipment.html
Go to this page 
Click to a product detail 
Scroll down 
Label will be disabled.
