### ISSUE TITLE
Search: Showing wrong results

### ISSUE THREAD

**Issue by MaxTa91** [Simicart/siminia-public#56]
# 🐞 Report

### Description

https://magento.pwa-commerce.com/men/tops-men.html?page=1&filter=%7B%22category_id%22%3A%5B%2236%22%5D%7D

It is showing the products from women cate. 

### Expected behaviour

Should be show correct results.

**Comment by codynguyen1** [comment]
https://github.com/Simicart/siminia-public/pull/57
Server is returning category options that's not right (not under parent cate).
So client will => Only show child cate options on filter.
