### ISSUE TITLE
My Account issues 

### ISSUE THREAD

**Issue by Watch3ruk** [Simicart/siminia-public#63]
When Login to my account : 

Tabs : 
Communications - **Sorry! An unexpected error occurred. Debug: ReferenceError54Q at render (/client.502b761b71afd0e8bc51.js:2046:2482)** 

Saved Payments - The Left side menu disappears . 

Address Book - not certain if on purpose but CSS brakes alignment .

### Exception/Error message
Saved Payments
![Address Book - webstore - Google Chrome 18_01_2022 11_24_36](https://user-images.githubusercontent.com/48841019/149928852-4cd492c7-bde5-4db2-9ed0-121166589deb.png)
Address Book 
![Address Book - webstore - Google Chrome 18_01_2022 11_21_43](https://user-images.githubusercontent.com/48841019/149928982-0a9560ab-b8d5-467a-8f34-b0b307bc81ff.png)
Normal State : 
![Address Book - webstore - Google Chrome 18_01_2022 11_21_48](https://user-images.githubusercontent.com/48841019/149929100-7bad57a7-a99a-4cca-959e-7de4938492e5.png)

**Comment by codynguyen1** [comment]
@Watch3ruk 
For communication page, we have updated it on another issue.
For other problems, I'm adding bug tag to this issue and adding assignee soon.
