### ISSUE TITLE
Shop By Brand Feature

### ISSUE THREAD

**Issue by codynguyen1** [Simicart/siminia-public#7]
Shop By Brand Feature
Following: https://github.com/Simicart/shopbybrand-module-pwa-studio

**Comment by MaxTa91** [comment]
@nnduy1998 Thiếu hiện thị brand ở trang detail a đang check https://domaio.pwa-commerce.com/joust-duffle-bag.html

**Comment by MaxTa91** [comment]
@nnduy1998 https://domaio.pwa-commerce.com/brands/category/brand-category2.html
This page doesn't map "title" correctly.  ---> check https://domaio.pwa-commerce.com/brands.html, too. 
![Screen Shot 2022-01-14 at 12 06 40](https://user-images.githubusercontent.com/11706605/149454868-867f6283-6582-41f9-a79a-572475af260e.png)

2. Brand isn't shown at Filter (product listing page).

**Comment by MaxTa91** [comment]
@codynguyen1 @nnduy1998 Xem lại phần filter theo brand ở navigator
