### ISSUE TITLE
Product alerts  

### ISSUE THREAD

**Issue by Watch3ruk** [Simicart/siminia-public#79]
Adding Product alerts to Product . 

so customers can chose : notify when in stock , notify when price changes

**Comment by codynguyen1** [comment]
@Watch3ruk 
The product alert need extra extension to be installed, so it would need to be done on feature-rich branch, and we'd need to find a provider that get required the most to work with them for API.
We will consider adding this to project, thank you for your idea!

**Comment by Watch3ruk** [comment]
hi , 
they are build in magneto : 
https://docs.magento.com/user-guide/catalog/inventory-product-alerts.html
