### ISSUE TITLE
Reward Points Feature

### ISSUE THREAD

**Issue by codynguyen1** [Simicart/siminia-public#8]
Reward Points Feature
Following: https://github.com/Simicart/rewardpoints-module-pwa-studio

**Comment by MaxTa91** [comment]
@nguyensyhuong A login vào https://domaio.pwa-commerce.com/checkout 
thì đang bị lỗi reward point chú xem nhé.

**Comment by MaxTa91** [comment]
@nguyensyhuong h
1. Layout input point is broken when point is over 3 char.
2. Need to add a loading when click to apply button 
3. If I have total is $100, I spent 150p.= $150 ---> I don't see any warning or something like that.

**Comment by MaxTa91** [comment]
@nguyensyhuong Missing reward points (discount) at order history

**Comment by MaxTa91** [comment]
@nguyensyhuong fix xong thì báo anh nhé.

**Comment by nguyensyhuong** [comment]
đang đợi api của Mageplaza ạ
