### ISSUE TITLE
NativeInner - Products Listing

### ISSUE THREAD

**Issue by codynguyen1** [Simicart/siminia-public#89]
# 🚀 feature request
Products Listing

### Description

<img width="188" alt="Screenshot at Feb 14 17-09-31" src="https://user-images.githubusercontent.com/16347586/153843899-4f923d08-f8e9-4827-a669-31771eef0b8d.png">

 A clear and concise description of the problem or missing capability...

### Describe the solution you'd like

 If you have a solution in mind, please describe it.

**Comment by codynguyen1** [comment]
https://projects.invisionapp.com/d/main?origin=v7#/console/20656318/434345551/preview?scrollOffset=1427.77783203125

**Comment by alitonia** [comment]
@I will do it
