### ISSUE TITLE
Price in the Cart is without VAT 

### ISSUE THREAD

**Issue by Watch3ruk** [Simicart/siminia-public#99]
✍️ A clear and concise description of the problem...

When adding items to cart price is without VAT ( so is shipping ) 

![Untitled - Google Chrome 18_02_2022 08_38_20](https://user-images.githubusercontent.com/48841019/154648073-7d616ca6-ef05-4b1b-bfa6-ae6e1592fca3.png)

**Comment by Watch3ruk** [comment]
hi ,any update on this please ?

**Comment by alitonia** [comment]
Sorry, we were busy the last few days. I have seen the error and am working on it.

**Comment by codynguyen1** [comment]
Problem solved with hard-code on tax config (always show included tax value), developer can manually change it from src/simi/Helper/Pricing.js
